site_name: "Hazla Corta: Como migrar de Google"
site_description: Guías para migrar fuera de Google, hechas por Open Source eUC en colaboración con la FEUC.
copyright: |
  Guías para migrar fuera de Google.
  Mantenido por <a href="https://github.com/open-source-uc/hazla-corta/graphs/contributors" target="_blank" rel="noopener">colaboradores</a>
  en <a href="https://github.com/open-source-uc" target="_blank" rel="noopener">Open Source UC</a> en colaboración con la FEUC

repo_url: https://github.com/open-source-uc/hazla-corta-drive
edit_uri: edit/main/docs/

nav:
  - Inicio: index.md
  - Guía rápida:
      - Inicio: guia-rapida/index.md
      - Google Takeout: guia-rapida/google-takeout.md
      - Drive a OneDrive: guia-rapida/drive-a-onedrive.md
      - GMail a Outlook: guia-rapida/gmail-a-outlook.md
  - Información sobre el cambio: informacion-sobre-el-cambio.md
  - Guías por área:
      - Principales:
          - Drive: por-area/drive-personal.md
          - Calendario: por-area/calendario.md
          - Email: por-area/email.md
          - Contactos: por-area/contactos.md
      - Software asociado:
          - Cuentas Asociadas: por-area/cuentas-asociadas.md
          - Datos del Navegador: por-area/datos-navegador.md
      - Otros:
          - Unidades Compartidas: por-area/drive-unidades-compartidas.md
          - Notas (keep): por-area/notas.md
          - Ubicaciones (maps): por-area/ubicaciones.md
  - Como contribuir: contributing.md

markdown_extensions:
  - admonition
  - abbr
  - footnotes
  - pymdownx.superfences
  - def_list
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - git-revision-date-localized:
      locale: es

extra_css:
  - assets/style.css

theme:
  name: material
  custom_dir: overrides
  language: es
  logo: assets/osuc-feuc.svg
  favicon: assets/osuc-favicon.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.tabs
    - navigation.sections
    - search.highlight
  palette:
    - scheme: default
      primary: deep purple
      accent: deep purple
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: Cambiar a tema oscuro
    - scheme: slate
      primary: deep purple
      accent: deep purple
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-night
        name: Cambiar a tema claro

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://osuc.dev
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/OpenSource_eUC
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/opensource_euc/
    - icon: fontawesome/brands/github
      link: https://github.com/open-source-uc
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/open-source-euc
    - icon: fontawesome/brands/discord
      link: https://discord.gg/VMXCNAvjPW
